language: php
php:
  - "5.4"
#  - "5.3"
#  - "5.5"
env: DB=mysql
services: memcached
install: true
before_script:
  - mysql --execute="create database IF NOT EXISTS zencart;" --user=travis
#  - echo 'date.timezone = "Europe/London"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script:
  - phpunit testFramework/unittests/testTestCase.php
  - phpunit --configuration testFramework/webtests/phpunit.xml
