addons:
  sauce_connect:
    username: zencart
    access_key: f39f7296-a675-481f-a509-9cd78ad3c30b
language: php
php:
  - "5.4"
  - "5.5"
  - "5.3"
env:
  global:
  - DB=mysql
#services: memcached
install: true
branches:
  only:
    - v160
before_script:
  - mysql --execute="create database IF NOT EXISTS zencart;" --user=travis
  - echo 'date.timezone = "Europe/London"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script:
  - phpunit -c testFramework/unittests/phpunit.xml
